### ISSUE TITLE
Are there any examples apps

### ISSUE THREAD

**Issue by Jamalzahid** [dlgrech/ksol#2]
Would you please like to add some examples apps for this ksol library for solana transactions. Thanks a lot. waiting for example app

**Comment by dlgrech** [comment]
Hi there -

It depends what you're trying to do. 

[This class](https://github.com/dlgrech/ksol/blob/main/ksol-cli/src/main/kotlin/com/dgsd/ksol/cli/send/SendCommand.kt) shows off how to send a transaction using the library.

There are a bunch of examples [in the CLI](https://github.com/dlgrech/ksol/tree/main/ksol-cli/src/main/kotlin/com/dgsd/ksol/cli) of how to do various things.

Finally, if you're after an example of how to use the library in Android, I built a [non-custodial wallet](https://github.com/dlgrech/solar-wallet) based on this library
